language: rust
sudo: false
env:
  - FEATURES='serde-1'
matrix:
  include:
    - rust: 1.22.1
      env:
      - FEATURES='array-sizes-33-128 array-sizes-129-255'
    - rust: stable
    - rust: stable
      env:
        - FEATURES='serde-1'
    - rust: stable
      env:
      - FEATURES='array-sizes-33-128 array-sizes-129-255'
    - rust: beta
      env:
        - FEATURES='serde-1'
    - rust: nightly
      env:
      - FEATURES='serde-1'
    - rust: nightly
      env:
      - FEATURES='array-sizes-33-128 array-sizes-129-255'
branches:
  only:
    - master
    - 0.3
script:
  - |
      cargo build --verbose --no-default-features &&
      cargo build --verbose --features "$FEATURES" &&
      cargo test --verbose --features "$FEATURES" &&
      cargo test --release --verbose --features "$FEATURES" &&
      cargo bench --verbose --features "$FEATURES" --no-run &&
      cargo doc --verbose --features "$FEATURES"
