language: rust
sudo: false
env:
  - FEATURES='serde-1'
matrix:
  include:
    - rust: 1.21.0
    - rust: stable
      env:
        - NODEFAULT=1
    - rust: beta
    - rust: nightly
      env:
        - NODEFAULT=1
    - rust: nightly
    - rust: nightly
      env:
      - FEATURES='serde'
branches:
  only:
    - master
    - 0.3
script:
  - |
      cargo build --verbose --features "$FEATURES" &&
      ([ "$NODEFAULT" != 1 ] || cargo build --verbose --no-default-features) &&
      cargo test --verbose --features "$FEATURES" &&
      cargo test --release --verbose --features "$FEATURES" &&
      cargo bench --verbose --features "$FEATURES" -- --test &&
      cargo doc --verbose --features "$FEATURES"
