#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Generate ArrayVecCopy from ArrayVec
# Replace type name with ArrayVecCopy
# Insert `T: Copy` bound as needed.
#
# Replace `// DIRECTIVE ArrayVecCopy` with empty string anywhere to allow
# items to be cfg'ed out for arrayvec copy

sed \
       -e "s/\\<ArrayVec\\>/ArrayVecCopy/g" \
       -e "s/\\<ArrayVecVisitor\\>/ArrayVecCopyVisitor/g" \
       -e "s/impl<\\('[A-Za-z_]*, \\)\\?T:/impl<\\1T: Copy +/g" \
       -e "s/impl<\\('[A-Za-z_]*, \\)\\?T,/impl<\\1T: Copy,/g" \
       -e "s/struct \\([A-Za-z_]*\\)<\\('[A-Za-z_]*, \\)\\?T:/struct \\1<\\2T: Copy +/g" \
       -e "s/struct \\([A-Za-z_]*\\)<\\('[A-Za-z_]*, \\)\\?T,/struct \\1<\\2T: Copy,/g" \
       -e "s/fn \\([A-Za-z_]*\\)<\\('[A-Za-z_]*, \\)\\?T:/fn \\1<\\2T: Copy +/g" \
       -e "s/fn \\([A-Za-z_]*\\)<\\('[A-Za-z_]*, \\)\\?T,/fn \\1<\\2T: Copy,/g" \
       -e "s/const fn/fn/" \
       -e "s/\\/\\/ DIRECTIVE ArrayVecCopy \\+//" \
       src/arrayvec.rs \
       > src/arrayvec_copy_generated.rs

mv -v -f src/arrayvec_copy_generated.rs src/arrayvec_copy.rs
